name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: Go Release Binaries
      uses: wangyoucao577/go-release-action@v1.17
      with:
        # GITHUB_TOKEN for uploading releases to Github asserts.
        github_token: ${{ secrets.GO_RELEASER_GITHUB_TOKEN }}
        # GOOS is the running programs operating system target: one of darwin, freebsd, linux, and so on.
        goos: linux
